name: FOSSA
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19.x"
      - run: go version
      # Runs a set of commands to initialize and analyze with FOSSA
      
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
